services:
  mysql:
    image: mysql:8.0
    container_name: miniurl-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: miniurl
      MYSQL_USER: miniurl
      MYSQL_PASSWORD: miniurl
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend/
    container_name: miniurl-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/miniurl
      SPRING_DATASOURCE_USERNAME: miniurl
      SPRING_DATASOURCE_PASSWORD: miniurl
    ports:
      - "8080:8080"

volumes:
  mysql-data:
